### ISSUE TITLE
Look ahead Variables

### ISSUE THREAD

**Issue by rafaelkrause** [codeplea/tinyexpr#102]
Hello all,

We just wrote a code example to "look ahead" variables inside a expression. Some times We don't know the name of variables used on a expression, so, is nice to pickup that variables inside a expression and performe some variable checking or build a list, before pass to te_compile.

Please feel free to use if it is useful.

```c
char ** te_get_variables(const char *expression, int* total_vars)
{
	int alloc_vars = 20;	// Pre-allocation
	int var_cnt		= 0;

	char ** var_list = (char **)malloc(alloc_vars * sizeof(char *));
	CHECK_NULL(var_list);

	memset(var_list, 0, alloc_vars * sizeof(char *));

	state s;
	s.start = s.next = expression;
	s.type = TOK_NULL;

	do 
	{
		if (!*s.next) 
		{
			s.type = TOK_END;
			goto end;
		}

		/* Try reading a number. */
		if ((s.next[0] >= '0' && s.next[0] <= '9') || s.next[0] == '.') 
		{
			s.value = strtod(s.next, (char**)&s.next);
		}
		else 
		{
			/* Look for a variable or builtin function call. */
			if (isalpha(s.next[0])) 
			{
				const char *start;
				start = s.next;
				while (isalpha(s.next[0]) || isdigit(s.next[0]) || (s.next[0] == '_')) s.next++;

				const te_variable *var = find_builtin(start, s.next - start);
				if (!var)
				{
					if (var_cnt < alloc_vars - 2)
					{
						alloc_vars *= 2;
						var_list = realloc(var_list, alloc_vars);
						CHECK_NULL(var_list);
					}

					int nameLen = s.next - start;
					var_list[var_cnt] = (char*)malloc(nameLen + 1);
					CHECK_NULL(var_list[var_cnt]);

					memcpy(var_list[var_cnt], start, nameLen);
					var_list[var_cnt][nameLen] = '\0';
					var_cnt++;
				}
			}

			s.next++;
		}
	
	} while (s.type == TOK_NULL);

end:
	if (var_cnt == 0)
		free(var_list);

	if (total_vars)
		*total_vars = var_cnt;

	return var_list;
}

```

**Comment by fineless71** [comment]
Could you provide the full code, like the `find_builtin` function, `state` struct, etc. Thanks.

**Comment by alphaKilo74** [comment]
Are you shure with this line?
   if (var_cnt < alloc_vars - 2)
at the beginning var_cnt is 0 and alloc_vars is 20 an then you increase alloc_vars (alloc_vars *= 2;)

**Comment by alphaKilo74** [comment]
If an expression ends with an variable then this function jumps over the end.
I think you should add one line

  `
            var_list[var_cnt][nameLen] = '\0';
            var_cnt++;
         }
      }
      **_if( s.next[0] != '\0' )_**
         s.next++;
   }
} while (s.type == TOK_NULL);`
