### ISSUE TITLE
Custom infix operators

### ISSUE THREAD

**Issue by Heath123** [codeplea/tinyexpr#103]
The infix operators seem to be hardcoded. In some cases it would be useful to change the function they call, the characters (or sequences of characters) used, or add and remove them.

**Comment by Blake-Madden** [comment]
Just curious, which sort of operators would you like to add?

**Comment by Heath123** [comment]
In my case I wanted to change the operators to different ASCII values, and maybe add some extras, as I'm trying to parse an expression in a non-standard format that my calculator's OS uses. I looked at the code a bit more, and I think it would be better for me to just edit the code directly, since a lot of it is hardcoded
