### ISSUE TITLE
Redundant null-pointer check in `te_interp`

### ISSUE THREAD

**Issue by ParticleG** [codeplea/tinyexpr#111]
At [tinyexpr.c#L695](https://github.com/codeplea/tinyexpr/blob/5c3dd60afa919a0f0335910f8ad95f24435a197a/tinyexpr.c#L695) there's already a NULL check. But at L700 check for NULL again immediately. Should the later check be removed?

**Comment by codeplea** [comment]
Indeed. I removed it. Thanks.
