### ISSUE TITLE
does not support variables with underscore

### ISSUE THREAD

**Issue by salos1982** [codeplea/tinyexpr#12]
i have variable with underscore, e.g. my_var. There is parsing erorr

**Comment by codeplea** [comment]
Tinyexpr supports variables starting with a lower-case letter and containing only lower-case letters and numbers. You should be able to change that at tinyexpr.c:207 and tinyexpr.c:210.

**Comment by codeplea** [comment]
I added support for underscores in variable names (but not as the first character).

**Comment by aster2013** [comment]
Please add support for variable name with underscore as the first character.

```cpp
double a;
    double b;
    te_variable variables[] = {
        { "_a", &a },
        { "_b", &b },
    };
    int err;
    te_expr* expr = te_compile("sqrt(_a^2+_b^2)", variables, 2, &err);
```

**Comment by codeplea** [comment]
Just add something like `|| (s->next[0] == '_')` to line [255 of tinyexpr.c](https://github.com/codeplea/tinyexpr/blob/373d2d3d5dc3344e3e2cb826717404064562a058/tinyexpr.c#L255).
