### ISSUE TITLE
Default Exponentiation Behavior

### ISSUE THREAD

**Issue by mogando668** [codeplea/tinyexpr#121]
> By default, TinyExpr does exponentiation from left to right. For example:
> 
> a^b^c == (a^b)^c and -a^b == (-a)^b
> 
> This is by design. It's the way that spreadsheets do it (e.g. Excel, Google Sheets).
> 
> If you would rather have exponentiation work from right to left, you need to define TE_POW_FROM_RIGHT when compiling tinyexpr.c. There is a commented-out define near the top of that file. With this option enabled, the behaviour is:
> 
> a^b^c == a^(b^c) and -a^b == -(a^b)
> 
> That will match how many scripting languages do it (e.g. Python, Ruby).

How Excel does it is the super minority. Not only does nearly everyone else does it right-to-left, such as `bc`, `WolframAlpha`, `python`, `awk`, etc etc, that's also its official mathematical definitions (see wiki links below)

https://en.wikipedia.org/wiki/Exponentiation#Integer_exponents
https://en.wikipedia.org/wiki/Exponentiation#Identities_and_properties

Google Sheets only does it their way because they're trying to maximize Excel compatibility, which involves taking on all of Excel's design flaws as their own as well.

Evaluation of ANY chain any of the same math operator should be thought of descending down a stack of operands.

Say  79 % 37 % 3 ==

```
     79
           % 
                 37
                        % 
                              3
```

which becomes  `79 % 37 % 3 => (79 % 37) % 3 => ( 5 ) % 3 => 2`

But if one does it bottom up,

`79 % ( 37 % 3) => 79 % ( 1 ) => 0`

SImilarly, the mathematical stack for 8 ^ 7 ^ 3 is 

```
                     3
              7
      8
```

….. so once you fill in the operator (`^`) in between …..

```
                     3
                  ^ 
              7
          ^ 
      8
```

it should evaluate to `8 ^ ( 7 ^ 3 ) => 8 ^ ( 343 ) => 2 ^ 1029`, a number beyond the largest exponent of the double precision floating point data type,

whereas Excel goes against all mathematical definitions, and ending up with

`( 8 ^ 7 ) ^ 3 => ( 2 ^ 21 ) ^ 3 => 2 ^ 63`

which is only half way to `UINT_64_MAX`

The situation is much worse when some of the exponents are fractions (i.e. nth-roots)

say` 2 ^ 9 ^ ( 1 / 2 )`

Doing the standard way, that's just ` 2 ^ sqrt( 9 ) => 2 ^ 3 => 8`

But to do it incorrectly left to right, it becomes

`( 2 ^ 9 )^( 1 / 2 ) => sqrt( 512 )`

which is an irrational number that's nearly` 8 x 3.`

Sometimes the consequences can be severe : 

`0 ^ 0 ^ 0 `  ::::

standard right-to-left is` 0 ^ ( 0 ^ 0 ) => 0 ^ ( 1 ) => 0`

but left to right is `( 0 ^ 0 ) ^ 0 => ( 1 ) ^ 0 => 1`

If used in the boolean context, one has just fully inverted the outcome.

A very long chain of `0 ^ 0 ^ 0 ^ 0 ^ 0 ^ 0 ^ …… ^ 0` would also behave drastically different - left-to-right would always yield a 1 any chain non-zero-length chain.

But in the standard right-to-left context, the resulting value will continuously oscillate between 1 and 0, and the 1 outcome happening whenever total number of power operators  ( `^` ) is odd, as if one has applied `% 2` instead.

In the worst case, like `0 ^ 1 ^ ( -1 )`, right-to-left is` 0 ^ ( 1 ^ ( -1 ) ) => 0 ^ 1 => 0`.

but with left-to-right, `( 0 ^ 1 ) ^ ( -1 ) => 0 ^ ( -1 ) => +infinity`, two outcomes that cannot be any further apart in the unsigned sense.

I sincerely hope you would consider altering TinyExpr's default behavior to make left-to-right the default, while allowing users to set the configuration parameter if they so desire right-to-left.

**Comment by codeplea** [comment]
TinyExpr is about 10 years old now. This issue has been brought to my attention regularly from nearly the first day TinyExpr was published here.

The reason TinyExpr was made in the first place was to be used in a spread-sheet like program, so Excel compatibility made sense at the time. If I had it to do over today, I probably would do right-to-left instead.

However, the design choice was made a long time ago, and changing it now would silently break things for existing users. **So without extraordinary justification, I will not be changing the default. You can get right-to-left with a compile time flag, if that's what you want.**

>How Excel does it is the super minority.

This isn't true. Excel almost certainly has more users than the other examples you mentioned combined. See also Matlab - software made specifically for mathematicians - which uses left-to-right.

> that's also its official mathematical definitions (see wiki links below)

The wiki links don't support your claim. It says "conventional order of operations for serial exponentiation in superscript notation is top-down (or right-associative), not bottom-up." Unfortunately, we don't have *superscript* notation. TinyExpr has no concept of up/down at all.

> it should evaluate to 8 ^ ( 7 ^ 3 ) => 8 ^ ( 343 ) => 2 ^ 1029, a number beyond the largest exponent of the double

This isn't useful. You're complaining that TinyExpr returns an incorrect result, but you just want it to return a different incorrect result instead.

> But to do it incorrectly left to right, it becomes ( 2 ^ 9 )^( 1 / 2 ) => sqrt( 512 ) which is an irrational number that's nearly 8 x 3.

TinyExpr won't generally return irrational numbers.

> Sometimes the consequences can be severe : 0 ^ 0 ^ 0 ::::

Zero to the power of zero isn't even itself well-defined without context. https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero

TinyExpr isn't pure math. It's a computer program with a concrete implementation, and therefor approximations and compromises have to be made. I prefer the set of compromises I made at the time I made them. 

I'm closing this topic, but I am curious about one thing if you want to follow-up. Did this surprise behavior cause a problem for you personally in production? Or did you simply notice it in the readme before deciding to open this issue?

**Comment by mogando668** [comment]
it should evaluate to 8 ^ ( 7 ^ 3 ) => 8 ^ ( 343 ) => 2 ^ 1029, a number beyond the largest exponent of the double
This isn't useful. You're complaining that TinyExpr returns an incorrect result, but you just want it to return a different incorrect result instead.

you clearly missed the point. 4^( 3^3 ) == 2^54, but ( 4^3 )^3 == 2^18. 

with right-to-left, just writing 2^4^8 already gets you to 2^65536, while ( 2^4 )^8 is barely 2^32

As for powers of 0, even if we ignore zeroth power, left-to-right runs into this issue ::

( 0 )^( -1 )^( 2 )

right to left is just ( 0 )^( (-1)^2 ) := ( 0 )^( 1 ) := 0, a very safe number

left to right is ( 0^(-1) )^2 := ( infinity )^2. You really think squaring infinity is the proper calculation here ?
