### ISSUE TITLE
Using uint64_t instead of double

### ISSUE THREAD

**Issue by emoon** [codeplea/tinyexpr#13]
Hi,

I have been thinking about using your library with uint64_t instead of doubles and only use it for integer expressions (so things like  `sin(x)` will not work, this is fine)

I wonder if you see any issues with that or that it should work fine to replace all floats with uint64_t?

**Comment by codeplea** [comment]
I can't think of any obvious issue with that. Try it out, and let me know.

**Comment by emoon** [comment]
Alright. Will do. Thanks!

**Comment by EvilPudding** [comment]
It will probably have problems if you try to do subtractions though.

**Comment by emoon** [comment]
Yeah so I plan to use it in debugger for calculating expressions for which memory address to view for example like : `0x0000124 + 12`

**Comment by codeplea** [comment]
Currently it uses `strtod` to parse numbers (`tinyexpr.c:203`), so the 0x0000 will trip it up. It should be quite easy to change though. Let me know if you run into any problems, and I can help.

> It will probably have problems if you try to do subtractions though.
Why do you say that?

**Comment by EvilPudding** [comment]
Because it might easily cause underflows, and it would have problems in this function
```c
static double negate(double a) {return -a;}
```

**Comment by codeplea** [comment]
Oh, I didn't notice the `u`. Well, I think these are all issues with unsigned math in general.

**Comment by EvilPudding** [comment]
Of course, just giving a heads up. Though in C, you can have unsigned subtraction, it works if it doesn't underflow, I guess it works as well here because you're using a subtract function instead of applying the negate to all `-`.

**Comment by codeplea** [comment]
Correct me if I'm wrong, but I believe that in most C implementations (assuming two's complement), `a + (-b)` is still the same as `a-b`, even if both `a` and `b` are unsigned. It does underflow (obviously), but the math still works out the same in the end.

Anyway, moot point. TinyExpr does implement subtraction, so at the end of the day it should work the same as in C, whatever that happens to be.

**Comment by emoon** [comment]
Also in my case it really doesn't matter that much. If the user puts in something "wrong" and the result becomes negative other parts of the code will handle a "negative" address (as this will be used to input CPU addresses and thus I need it to be fully 64-bit)

**Comment by EvilPudding** [comment]
I had no idea you optimized as C does for `a + (-b)`, just tested it, works perfectly.

**Comment by emoon** [comment]
Just wanted to say this all works fine. Cheers!
