### ISSUE TITLE
Add support for factorials

### ISSUE THREAD

**Issue by vktec** [codeplea/tinyexpr#14]
Ideally, `5!` would be equivalent to `5*4*3*2`, which could be implemented using a recursive function:

```c
double factorial(double n) {
  if (n < 1) {
    return 1;
  }

  return n * factorial(n - 1);
}
```

Of course, some error checking would be required, as calculating the factorial of negatives or fractional numbers is invalid.

**Comment by codeplea** [comment]
I think this might be out of the scope of a library called **Tiny**Expr, but I'm open to discussion.

What use-case do you have where needing the factorial syntax is important? Would implementing a function be much worse? i.e. is `5!` substantially better than `fac 5` or `fac(5)`?

Which other programming languages provide this syntax? Are we going for compatibility with them?

Also, where does it fit into the operator precedence? Is there even a well-agreed upon standard? Does `5*5!` mean `(5*5)!` or `5*(5!)`?

In addition to negative or non-whole numbers, there is the also issue of large numbers, particularly if a recursive or iterative function is used to calculate with. (Although I am sure that recursion is not the best way to implement this in C.)

**Comment by EvilPudding** [comment]
I think it would take the highest precedence between unary operators, so `-x!` would mean `(-x)!` and not `-(x!)`. though that's just my intuition talking.

I don't see a reason not to implement this, it might help in some cases and the code needed for it is pretty small. Though it would need to be documented, since `!` isn't widely accepted as factorial outside of mathematics.

**Comment by vktec** [comment]
@codeplea, factorials have higher operator preference than anything else other than brackets. `5*5!` means `5*(5!)`, `-5!` means `-(5!)`, etc.

A function wouldn't be too bad, but as TinyExpr aims to parse *math* expressions, it would probably be better to go with the mathematical syntax for this. I agree with @EvilPudding that this should be documented though, as it could come as a surprise to some people.

I do think this would be useful in TinyExpr, as it probably wouldn't take *that* much code to implement and is used in several places in mathematics. It also provides a building block that can be used to do things like combinations and permutations.

**Comment by codeplea** [comment]
Another issue with using the `!` operator for this is that many expect it to represent logical negation. If logic operators get added in the future, it'll be confusing.

**Comment by vktec** [comment]
Ah, that's true. Perhaps using a function for factorial would be better, in that case.

Alternatively, `~` could be used for logical negation, as that's probably the second most common syntax and makes more sense in terms of boolean algebra, where negation is represented by a horizontal line over an expression.

**Comment by EvilPudding** [comment]
This is the problem, for different contexts, it's expected different notations, if there was a way to just assign operators to functions even if at compile time, it would solve a lot of issues.

**Comment by codeplea** [comment]
Support for factorials has been added (thanks chendotjs).

e.g. `fac 5` == 120
