### ISSUE TITLE
Add support for combinations and permutations

### ISSUE THREAD

**Issue by vktec** [codeplea/tinyexpr#15]
`nCr` and `nPr`, while achievable with factorials (see #14),  would be nice to have as "helpers".

```c
double npr(double n, double r) {
  return factorial(n) / factorial(n - r);
}

double ncr(double n, double r) {
  return factorial(n) / (factorial(r) * factorial(n - r));
}
```

As with factorials, some checks are required to ensure that people don't get unexpected results from negative or fractional numbers.

**Comment by codeplea** [comment]
What would the parsing syntax look like? Do you intend these to be infix operators?

**Comment by vktec** [comment]
@EvilPudding, ooh, nice idea. Being able to extend TinyExpr would open up a lot of possibilities and a lot more applications would be possible. For example, one could add support for algebraic equations and plot graph functions with it.

**Comment by vktec** [comment]
@codeplea, infix operators would be ideal (`5C3`, `10P4`, etc) but functions would also work (`ncr(5, 3)`, `npr(10, 4)`, etc).

**Comment by codeplea** [comment]
I don't think there will be any way to allow user-defined operators and still keep TinyExpr's simple recursive descent parsing code. The best feature of TinyExpr, in my opinion, is that it is simple and easy for others to add to. If I add a bunch of stuff, it's no longer simple or easy to add to.

And honestly, TinyExpr wasn't designed for having operators added at runtime. If that was a design goal, using Dijkstra's shunting-yard algorithm and a stack machine would be much better than recursive descent. In that case, the operators can simply exist in a table with their respective precedence and associativity. I wrote Javascript code for that a few years ago, maybe I should open-source it.

**Comment by vktec** [comment]
Fair enough. TinyExpr is so small there's not much harm in copying the directly into your project and then modifying it to add other operators, etc.

**Comment by EvilPudding** [comment]
@codeplea I did say compile time, for runtime operators would have to change 90% of the code.

**Comment by codeplea** [comment]
Functions `ncr` and `npr` have been added. (thanks chendotjs)
