### ISSUE TITLE
power

### ISSUE THREAD

**Issue by EvilPudding** [codeplea/tinyexpr#2]
I have a project where I solve mathematical expressions using OpenCL, but
as as a fallback to devices that do not support GPU acceleration, I'm using
this library, but there is one problem, the difference in syntax of the
power function.

In OpenCL, which is a subset of C99, there is no '^', so every time I use
'a ^ b' in the expression, I would have to parse it and substitute for
'pow(a, b)', and that could be a complicated expression to parse. And
because there is no 'pow' in this lib, I would have to do the reverse if I
decided to stick to only using 'pow'.
This made me want to either add pow to the builtin functions, or something
even better; I would like to suggest adding the capability to define custom
functions to the library. The only problem with this would be that right
now, builtin functions are constant, so there would be two options:

1. Change all functions to one dynamic array.
   - Pros: Only needs one binary search.
   - Cons: There would need be an init call to fill the builtin functions,
   or the first call to any function would have to check if the functions
   were initialized.

2. Keep the constant builtin array, and one dynamic array for custom
functions.
  - Pros: No need for initialization; Possibility to override builtin
  functions by searching the custom functions before searching the builtin
  ones.
  - Cons: Two binary searches would have to be performed.

The syntax for it would probably look something like this:
```c
te_func("pow", my_power_function);
```

Then, when using it in the expression, it would count the number of
arguments being used, and assume that the function receives that number of
arguments, and cast it to '(double)(*func)(double, double)'
The only problem with that approach would be that if the user uses a wrong
number of arguments by mistake, the result would be unexpected, and depend
on the C implementation.

An alternative would be to explicitly state the number of arguments:
```c
te_func("pow", my_power_function, 2);
```

Making it so it's cast to the right type, and add the possibility to return
an error if the user calls it with a wrong number of arguments.

**Comment by codeplea** [comment]
Hi EvilPudding,

I can probably add something like this. I was thinking about doing it anyway, because it will be helpful in one of my other projects.

First off, I won't have mutable global state, so modifying the built-in function list at run-time is out. (Although if I support arity 2 functions, I'll probably just add `pow` and `atan2` to that list since they are in ANSI C).

I was actually thinking that dynamic function calls could be an extension to the variable lookup list it takes now. For example, right now you can pass in variables such as:

```C
    double x, y;
    te_variable lookup[] = {{"x", &x}, {"y", &y}};
    te_expr *expr1 = te_compile("x ^ y", lookup, 2, 0);
```
I'm thinking about adding a third required value, the arity, which is set to 0 for variables, 1 or more for functions. So your `pow` function would have arity 2. The interface would look like this:

```C
    double x, y;
    te_variable lookup[] = {{"x", &x, 0}, {"y", &y, 0}, {"pow", my_power_function, 2}};
    te_expr *expr2 = te_compile("pow(x, y)", lookup, 3, 0);
```

The implementation would still use the linear search in `find_var()`. I think it is too much to ask the caller to sort their variables.

Another thing is that the parser doesn't currently support functions with arity other than 1. I'll have to extend that. It'll have to parse commas. Also, having functions with arity more than two will be tricky. Right now the `te_expr` structure stores `right` and `left` pointers.

Let me know your thoughts, and maybe I'll poke around with it in the meantime.

**Comment by EvilPudding** [comment]
I think most users would find it wierd to add a 0 to variables, when they
may not even understand arity, although, it works perfectly, because if you
don't initialize the structure with explicit arity, it will default to 0,
and that would keep older code compatible.

I think it is an elegant solution, although it would mean that if you use
multiple calls in different parts of your code, you would have to redefine
the functions in the lookup, which may or may not be a problem. Another way
would be for the user to keep his common lookup array, and have te_compile
be able to recieve multiple lookups, so it would give more power to the
user.

I would also suggest removing the var_count, and just have the array be
NULL terminated, because I might constantly be changing the variables I
use, and I don't like counting them that much.

What I'm proposing would look like this:

```c
te_expr *te_compile(const char *expression, int error, int lookup_count, ...);
```

And then it could be used like so:

```c
te_variables common_vars[] = {{"pow", my_power_function, 2}, NULL};

te_expr *expr1 = te_compile("pow(x, y)", NULL, 2, common_vars,
      {{"x", &x}, {"y", &y}, NULL});

te_expr *expr2 = te_compile("pow(z, w)/t", NULL, 2, common_vars,
      {{"z", &z}, {"w", &w}, {"t", &t}, NULL});
```

The problem with this change is that it wouldn't stay compatible with older
code. But then the user could create all sorts of different groups of
lookups. Another issue would be that maybe the lookup count wouldn't be as
intuitive as having just one.

It's completely understandable if you decide to keep the same te_compile
signature as you have it now, it's just a thought.

As to the having comma separated functions, that seems easy enough to
accomplish, seen you already have binary operators.

If we decide to allow more than two arguments per function, we would just
have to make the left and right be an array allocated right below the
structure so there aren't further cache misses, which would be simple
enough.

Another thing I'm trying to imagine is custom operators, which would not
fit the model, seen they could have the same arity as functions, and in a
certain way _are_ functions.

**Comment by EvilPudding** [comment]
Fore arity > 2, the new te_expr struct would look something like this:
```c
typedef struct te_expr {
    union {double value; te_fun1 f1; te_fun2 f2; te_fun3 f3 ..............};
    const double *bound;
    struct te_expr *members[];
} te_expr;

/* ... */

static te_expr *new_expr(te_expr *exprs[], int expr_count) {
    int members_size = sizeof(te_expr*) * expr_count;
    /* Allocating the te_expr like so will make it so there are no more cache misses than before */
    te_expr *ret = malloc(sizeof(te_expr) + members_size);
    /* By using memcpy instead of a loop, we're barely losing any time */
    memcpy(ret->members, exprs, members_size);
    ret->bound = 0;
    return ret;
}

```

**Comment by EvilPudding** [comment]
Also, I think it would be better to have only one find function, and have
the builtin functions be _te_variable_ for consistency.
This would mean the lookup would have to be sorted, which would a very easy
thing to do.

**Comment by codeplea** [comment]
I just pushed a new branch where I've started work on this. Please take a look.

I've added the comma operator, which works as in C. I've added the ability for the built-in functions to have arity 0 or 2 instead of just 1. I've added to the built-ins `pow` and `atan2`. I've also added the constants `pi` and `e`.

I'm reluctant to support arity > 2 without a solid use-case need. Also, I'm still thinking about the best way to allow for dynamic functions. I'll re-read what you've said and think on it some more.

Thanks for your feedback, you've definitely put some thought into it. I'll try to have a proper response for you later.

**Comment by EvilPudding** [comment]
Now that you can receive pointers to vars in the builtin, why have a
builtin type?

I'd started to make it so builtin is just te_variable, and te_variable has
the arity as the third member.

Even if we don't get to support arity > 2, having one lookup array only is
the best way to go in my opinion:

```c
/* in next_token() */
const double *var = find_var(s->lookup, s->lookup_len, start, s->next - start);
if(!var)
{
  s->var = var;
  if (var->arity == 0)
  {
    s->type = TOK_VARIABLE;
  } else {
    if (s->next - start > 15) {
      s->type = TOK_ERROR;
    } else {
      s->type = TOK_FUNCTION1;
    }
  }
}
```

And if the lookup isn't merged, having one find function would look like
this:

```c
/* in next_token() */
const double *var = find_var(s->lookup, s->lookup_len, start, s->next - start)
                    || find_var(builtin, builtin_len, start, s->next - start);
/* ... */
```

I renamed _functions_ to _builtin_, because I changed it's type to
_te_variable[]_, requiring a more descriptive name.

**Comment by codeplea** [comment]
I've been thinking about the approach that variables have arity 0, and I'm not sure it's the best idea. I can imagine a function of arity 0 being useful if it has side effects. So maybe I'll code variables as arity -1, which would just be a special code at that point.

**Comment by EvilPudding** [comment]
I don't think side effects are a very good idea in a mathematical library,
and in terms of computational logic it really makes sense, and making
variables -1 would mean they would arity would have to be explicit, while
in state changing functions (which in my opinion should not exist, and if
they exist would be a rare case), it could be implicit.
And seen state changing functions return nothing, how would you include
them in a math expression without creating your own programming language
in the process?

**Comment by codeplea** [comment]
Okay, I pushed some new code. It now supports dynamic functions.

```C
double test0() {
    return 6;
}

double test1(double a) {
    return a * 2;
}

double test2(double a, double b) {
    return a + b;
}

double x; 
te_variable lookup[] = {
    {"x", &x}, /* Compatible with existing interface because TE_VARIABLE=0. */
    {"test0", test0, TE_FUNCTION0},
    {"test1", test1, TE_FUNCTION1},
    {"test2", test2, TE_FUNCTION2},
};
te_expr *ex = te_compile(expr, lookup, sizeof(lookup), &err);
```

The thing is, if I allow outside functions at all, I can't stop side-effects. So I may as well plan for them.

I guess arity 0 functions could be useful, for example a function `get_time` could take no parameters and return the current system time. It could also be a variable, of course, but somehow an arity 0 functions feels better.

Also, note the `sizeof(lookup)`. Maybe that can be a fix for you not liking to count the `lookup` size?

Just to be clear, every function must return a double. I have *no* intention for allowing functions to return nothing. However, I have implemented the comma operator now, so you could evaluate something like: `set_speed(6*4), set_position(get_position + get_speed * get_elapsed), beep, whatever` and have it evaluate in a meaningful manner.

I should probably add `()` optional to arity 0 functions.

**Comment by codeplea** [comment]
So I'm fairly happen with where this is going. I still need to add a bunch of tests for the new features and update the documentation before merging it back into master.

I've kept find_var and find_function separate (although I should probably rename them for clarity). My thought is that the built-ins are useful, and there are a lot of them. So it makes sense to use the binary search for those. For runtime variables/functions, I feel like a binary search is overkill. Most callers, I expect, will only have 1 or 2 variables/functions they want to add.

**Comment by codeplea** [comment]
Something I've lost, is that the `optimize` function doesn't make sense when considering outside functions that may have side effects.

Again, I'm not necessarily in favor of side effects, but there's going to be no way to prevent them. I guess I'll re-code `optimize` to only work out built-ins.

**Comment by EvilPudding** [comment]
You can pretty much mark this issue as closed, works great.
I did find some odd things that I did not understand, like the _power_ function
that is called on the TOK_FUNCTION1 switch case, but I'll try understanding
later.
Another thing I didn't understand is why `optimize` no longer works,
from what I've seen, you need only check if it is a builtin function call, or even better:
```c
te_variable lookup[] = {
    {"x", &x}, /* Compatible with existing interface because TE_VARIABLE=0. */
    {"test0", test0, TE_FUNCTION0 | TE_STATELESS}, /** Meaning it can be optimized */
    {"test2", test2, TE_FUNCTION2}
};
```
Or have side effects be explicit `TE_SIDEEFFECTS`, but then wierd things
would happen to those who did not read they needed to explicitly say it has
side effects, and they would expect one result and get something weird, and
spend weeks debugging. While if the lack of side effects is the one which has
to be explicit, everything works as expected, but if they need to optimize further,
they can explore and discover that option, what do you think?
