### ISSUE TITLE
Compiler warning - fix

### ISSUE THREAD

**Issue by Nom-DePlume** [codeplea/tinyexpr#21]
A trivial fix and I do not know if this violates some style guide you adhere to or not (it certainly doesnt look as neat as the original).  

In tinyexpr.c comma does not use 'a'.  This generates a warning if -Wunused-variable is enabled.  The easy fix is just to cast it as a void as follows (pragma instructions are too compiler dependent).
`static double comma(double a, double b) {(void)a; return b;}`

Since its just 1 line I did not attach a diff or do a pull request.

**Comment by codeplea** [comment]
Thanks for bringing this to my attention. I will implement the fix soon, as you suggest.

**Comment by codeplea** [comment]
I made the change as you suggested. Thanks!
