### ISSUE TITLE
Undefined reference to 'fabs' on arduino ide 1.8

### ISSUE THREAD

**Issue by ricxsar** [codeplea/tinyexpr#22]
Hi. 
Thanks for the wonderful library. 

I am trying to include your library of one of my projects. When compiling, it returns an error.

```
#include "tinyexpr.h"

void setup() {
  // put your setup code here, to run once:
  te_interp("5*5", 0);
}

void loop() {
  // put your main code here, to run repeatedly:

}
```

```
/tmp/cce6imJi.ltrans0.ltrans.o:(.rodata+0x2): undefined reference to `fabs'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino/Genuino Uno.

```
I tried to compile simple arduino program using only the math library and it works.

```
#include <math.h>

void setup() {
  // put your setup code here, to run once:
  fabs(-3);
}

void loop() {
  // put your main code here, to run repeatedly:

}
```
```


Sketch uses 444 bytes (1%) of program storage space. Maximum is 32256 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 2039 bytes for local variables. Maximum is 2048 bytes.
```

I love to use your library on embedded systems. I hope you can fix the issue. Thanks.

**Comment by codeplea** [comment]
What is the commandline you're using to compile?

Maybe you need something like the `-lm` flag to link in the math library?

I really don't know. You'll might have better luck posting in an Arduino forum. Please report back if you do figure it out, though.

**Comment by ricxsar** [comment]
I am not using command line to compile. I think the arduino ide automates the process. I will try to get help with the arduino forum. But likely they will respond to contact the author to fix the issue though.

**Comment by codeplea** [comment]
You should be able to see what the IDE is passing to the compiler somehow. I think it could be very helpful to know.

**Comment by codeplea** [comment]
I assume you've also added `tinyexpr.c` into your project somehow. You may need to make sure that it is being compiled as C and not as C++. Just a thought.

**Comment by ricxsar** [comment]
Yes, I setup the ide to include your library including the source and the header file. It don't complain about undefined reference to the first function in the library which is `te_interp` so the library is included in the right way. I think the error is somewhere in line 119 on `tinyexpr.c`.

```
static const te_variable functions[] = {
118	    /* must be in alphabetical order */
119	    {"abs", fabs,     TE_FUNCTION1 | TE_FLAG_PURE, 0},
```

**Comment by codeplea** [comment]
What happens if you comment out line 119? Does it then complain that `acos` (from line 120) is undefined?

It seems like it's not linking against the math library. The usual way to do that on gcc is with the `-lm` flag. It could also be a C to C++ name mangling issue.

It also may be that the Arduino doesn't support pointers to functions, in which case you'd be out of luck.

**Comment by ricxsar** [comment]
I tried your suggestion. It compiles successfully after commenting the `abs` line. Do you know what is happening?

**Comment by codeplea** [comment]
No, that's really odd. `fabs` is very much part of standard C.

TinyExpr should work fine with that line commented out, you just won't have access to the `abs` function (you could write your own very easily though).

You should ask someone who knows about Arduino and report back.

**Comment by ricxsar** [comment]
Ok. I will. Thanks for the heads up. 

By the way, can you add operations for bitwise operations like `AND`, `OR` and `NOT`?
Those operations are very important to embedded systems.

**Comment by codeplea** [comment]
TinyExpr works with floating point, so bitwise operators don't really make sense there.

You could probably fork TinyExpr to use integers (I know at least one person already has) and then add those operators yourself pretty easily.
