### ISSUE TITLE
Missing CMake build system support

### ISSUE THREAD

**Issue by jansvoboda11** [codeplea/tinyexpr#27]
Hi.

I think it would be nice to have the option to build with CMake.
A lot of new projects (including mine) make use of it.
Please, see my PR, thanks: #26

**Comment by LelixSuper** [comment]
If I can give my own opinion, CMake is not necessary for this project, because tinyexpr has few files. Instead of adding an unnecessary dependence, it is better to improve the current makefile.

**Comment by codeplea** [comment]
I agree that CMake is probably not appropriate for this project.

It does look like you put a lot of work into the pull request. This rejection is about the suitability of CMake for TinyExpr and not about the quality of your work.

The recommend way to use TinyExpr is to add it to the project you're using it in. It's only two files, so this is very easy. TinyExpr doesn't currently ship with any way to build it as a library. That's on purpose. The Makefile is only to build the examples and tests, so it's mostly intended for the developers. I think it is more than adequate as is. Most users don't care about that stuff, they only need to copy `tinyexpr.c` and `tinyexpr.h` to their project.

The other issue with having an additional build system is that I'll be the one stuck updating it. And I haven't used CMake in years.

**Comment by jansvoboda11** [comment]
Thanks for the explanation, I understand your desire to keep this project as simple as possible.

However, I don't see how you can easily pull TinyExpr bug fixes and new features if you just copy the code to your VCS. Is this really the way to go in C/C++ ecosystem? People willing to do that would be still able to do so, the addition of CMake support doesn't change anything for them.

The switch to CMake would not mean that you will be stuck updating it. You can just install it and run only when a major change in the build process is introduced. The only difference being in writing "cmake && make" instead of just "make".

**Comment by EvilPudding** [comment]
Still doesn't make much sense to be compiling benchmarks and tests while embedding this library.

**Comment by jansvoboda11** [comment]
CMake will compile tests and benchmarks only if you tell it to do so. As you can see, the options default to OFF:

```
option(build_tinyexpr_test "Build TinyExpr tests." OFF)
```

The main motivation for this PR is that if you are developing an application that needs math library, you are able to tell your CMake build configuration to download this Git repository and then just link the library to your executable, nothing else.

You don't have hunt for few random files on GitHub, copy-paste them to your VCS, write your own build configuration for TinyExpr and end up never updating its source again.

Moreover, CMake is great for cross-platform support - you can generate Visual Studio solution or Xcode project with CMake. With Makefile, you are tied to Unix environment.

If you really want to keep doing things the old way, feel free to close this issue and reject the PR.

**Comment by LelixSuper** [comment]
> The main motivation for this PR is that if you are developing an application that needs math library, you are able to tell your CMake build configuration to download this Git repository and then just link the library to your executable, nothing else.
>
>You don't have hunt for few random files on GitHub, copy-paste them to your VCS, write your own build configuration for TinyExpr and end up never updating its source again.

I'm working on a project that uses tinyexpr and a makefile build file: I downloaded this repository as a git submodule, and, since the current tinyexpr's makefile has not a target that builds only `tinyexpr.c`, I fixed my makefile. I added the `-I` flag with the path to the submodule (where there is the header file), and I added a simple target:

```
# This target builds the external library.
bin/tinyexpr.o : lib/tinyexpr/tinyexpr.c lib/tinyexpr/tinyexpr.h
	$(CC) -c -o $@ $< $(CTFLAGS)
```

> If you really want to keep doing things the old way, feel free to close this issue and reject the PR.

Lots of project still uses make, or autoconf; you can't say that this method is old, it is only a different approach. I think that for simple projects make is really good because it is simple, but if the community want to move to Cmake (I've never used it) I have not anything to answer back (probably I'll still use my solution). 

ps. I wan't to start flame between make vs Cmake.

**Comment by EvilPudding** [comment]
>The main motivation for this PR is that if you are developing an application that needs math library, you are able to tell your CMake build configuration to download this Git repository and then just link the library to your executable, nothing else.

Then why wouldn't the cmake configuration only build the object to be used in such a project? And if we decide it should have specific integration for projects that use cmake, why not add ant configuration, why not add qtmake configuration for projects that use the qt build system? While we're at it, add a code::blocks configuration. Where does it stop? Sounds to me that if you have specific tools that you use in your project then you should make the specific bridges.

**Comment by chendotjs** [comment]
If I can give my opinion, it doesn't make much sense adding CMake configuration . 
Tinyexpr is simple, only containing 2 files. Makefile in Tinyexpr is clear enough to guide you start using Tinyexpr. I'm sure those who are experienced in CMake  can add some rules easily when making Tinyexpr compatible with their project.

**Comment by codeplea** [comment]
Sorry, I just don't see a compelling reason to ship CMake configurations with TinyExpr. I'm closing this.
