### ISSUE TITLE
Tinyexpr fully libre and GNU ?

### ISSUE THREAD

**Issue by spartrekus** [codeplea/tinyexpr#30]
Hello,

I would like to ask if this project could be made available and allowed to be libre, GNU,... for *Unix* community?

ZLIB is compatible with GNU GPL, but the licence GNU GPL would be a nicer licensing.

Would it be possible?

Thank you
Best regards

More info: https://www.gnu.org/licenses/license-list.en.html

**Comment by codeplea** [comment]
Are you asking for dual licensing? What are you looking to do with it that you can't under the ZLIB license?

**Comment by spartrekus** [comment]
I am just thinking... 

Since I read that GNU is better than ZLIB, I favor usually GNU rather than others. 

GNU is on most open projects. 

Dual licensing is not possible.

**Comment by Yardanico** [comment]
@spartrekus who said you that GNU is better than Zlib, lol?

**Comment by EvilPudding** [comment]
@spartrekus I was expecting an objective answer listing the points that make GLP better... I am disappointed, could have been informative.

**Comment by codeplea** [comment]
I'm actually a big fan of the GPL, and I use it on some of my other projects. However, I think that ZLIB is a good fit for this project.

>Dual licensing is not possible.

Tons of projects have dual licensing with GPL and some other license.
