### ISSUE TITLE
Question regarding te_free()

### ISSUE THREAD

**Issue by cuinjune** [codeplea/tinyexpr#31]
Hi, This may be a stupid question but I wonder if I have to call `te_free() `even when `te_compile()` returns 0.

I mean do I need to free it only after `te_eval()` is called? or do I still need to free it even when `te_compile()` returns 0 so I don't call `te_eval()`?

Thanks in advance.

**Comment by EvilPudding** [comment]
If te_compile returns 0, there is nothing to free.

**Comment by cuinjune** [comment]
Thank you so much!!!

**Comment by codeplea** [comment]
It is safe to call `te_free()` on 0, but it is certainly not needed.
