### ISSUE TITLE
Is it possible to use array as variable?

### ISSUE THREAD

**Issue by cuinjune** [codeplea/tinyexpr#32]
Hi, I'm using TinyExpr for my project and I wonder If it would be possible to implement a special function that uses square brackets[] used to access array variables.

For example, If I have arr[1+2] in an expression, it will calculate 1+2 first, and then find *(arr + 3) to get the value.

Would it be too much complicated work to implement this feature? 

If not, any advise or guidance would be greatly appreciated.

**Comment by EvilPudding** [comment]
It doesn't sound complicated. Though it might be outside the scope of the library, I don't know.

I want to hear @codeplea's opinion on this.

**Comment by codeplea** [comment]
Why not just use a function?

```C
double arr[5] = {1,2,3,4,5};

double my_array(double a) {
    int i = a;
    if (i < 0 || i > 4) return 0.0;
    return arr[i];
}

te_variable vars[] = {
    {"arr", my_array, TE_FUNCTION1}
};

te_expr *n = te_compile("arr(1+2)", vars, 1, 0);
```

I think adding special syntax for supporting arrays with square brackets would be extra complexity with no real advantage. I'm open to hearing other opinions though.

**Comment by EvilPudding** [comment]
That's pretty smart, hadn't even thought of it. And it has the upside that the user may define what happens in case of going out of bounds.

**Comment by cuinjune** [comment]
Thanks @codeplea. That's a nice solution.
I totally agree with your opinion. You can close this issue if you want :)
