### ISSUE TITLE
Adding the random() function?

### ISSUE THREAD

**Issue by cuinjune** [codeplea/tinyexpr#33]
Hi, I'm trying to add a`random()` function that returns a random value within the specified range.

But if I use constants to get the random value (e.g. `random(1,4)`) then it seems to store the first returned value and not actually call `random()` function again which has to be called each time when I call `te_eval()`.

It seems to work only when I use a variable inside random (e.g. random(0, max)) which makes it called each time when `te_eval()` is called I think.

Is there any easy way to make the specific function be called each time when `te_eval()` is called? (without having to use any variable as function arguments)

Thank you in advance!

**Comment by EvilPudding** [comment]
Tinyexpr has the flag TE_FLAG_PURE to flag functions as having side effects or not, you are either flagging as pure, or there is a bug, can you paste the code of how you're defining it?

**Comment by cuinjune** [comment]
@EvilPudding I removed the TE_FLAG_PURE flag and it works fine now. Thank you so much for your help!
