### ISSUE TITLE
"initializer is not a constant" error in Visual Studio.

### ISSUE THREAD

**Issue by cuinjune** [codeplea/tinyexpr#34]
Hi, I tried to build tinyexpr using Visual Studio on Windows 10 but an error occurs saying "initializer is not a constant". 
<img width="517" alt="screen shot 2018-01-21 at 4 04 27 am" src="https://user-images.githubusercontent.com/24947986/35187119-327bff12-fe62-11e7-85f9-9be078e8de4b.png">
If I remove all elements in functions[] array, the error no longer occurred.
Could someone please teach me how to fix this error?
Thank you so much in advance!

**Comment by codeplea** [comment]
I don't have VS installed right now, so this is only a wild guess, but what would happen if you replace `TE_FUNCTION1 | TE_FLAG_PURE` with only `TE_FUNCTION1`? Please try that and let me know.

**Comment by EvilPudding** [comment]
It would be pretty sad if windows C compiler cannot solve that into a constant expression... It could also be that we are not feeding a size to that array. If all else fails, we might have to have `ifdef`s specific to that platform, and possibly add a constructor attribute to an initialization function... in gcc this would be easy, although I'm not aware of how it would work on Visual's C compiler.

**Comment by cuinjune** [comment]
@codeplea Hi, I actually modified the original code a bit. if you see my screenshot, I added 'f's to the end of the functions. (e.g acos -> acosf) 
Removing all these 'f's almost fixed the problem.
Now only two functions generate this error that are "ceil" and "floor".
These functions generate the error even after removing 'f's from the function.
Any idea why this happens and how can I use "ceil" and "floor" without the error?
Thank you so much.

**Comment by cuinjune** [comment]
I could totally fix this error by creating separate static functions like how `fac()`, `ncr()` and `npr()` are implemented.

For example for `ceil()`, I created this function.
`static double func_ceil(double a) {return ceil(a);}`

And then call this function when initializing the `te_variable functions[]`array.
`{"ceil", func_ceil,    TE_FUNCTION1 | TE_FLAG_PURE, 0},`

This way, I could avoid the weird "initializer is not a constant" error in Visual Studio.
Maybe you can apply this change to your code? (if you think it's important)
Thanks anyway!

**Comment by codeplea** [comment]
@cuinjune What version of Visual Studio are you using?

Here is [a discussion where someone else is having the same problem almost 10 years ago](https://social.msdn.microsoft.com/Forums/vstudio/en-US/d4d8caa7-73aa-45d8-aa50-f02fff58730f/c2099-initializer-is-not-a-constant-using-floor-in-c-file?forum=vclanguage). There are a few workaround ideas there too.

**Comment by cuinjune** [comment]
@codeplea Hey I just tried your link and I could fix the issue by simply adding the below two lines anywhere above `static const te_variable functions[] = {}`

```
#pragma function (ceil)
#pragma function (floor)
```
Now it works without the problem and it is a lot simpler than my above solution.
Thank you so much for your finding!
