### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by EvilPudding** [codeplea/tinyexpr#4]
What would you think of me adding the possibility to compile the
benchmarking tool with support for GNU's libmatheval, and other languages
commonly used to solve expressions in C like perl and python?
It wouldn't bring the libraries with the program, so there is no problem
about size. It would just add the possibility to test them in case the user
has them installed.

**Comment by codeplea** [comment]
I'd say go for it, although I don't expect to win. TinyExpr was made to be simple - fast is an accident. Still, it would be neat to know where we stand.

**Comment by EvilPudding** [comment]
I wouldn't be so sure, I've ran tests inside python, and they've been much slower overall, but I need to call them within a C loop so I'm sure.

**Comment by EvilPudding** [comment]
On the mean time, can we get a flag that means the function is constant, meaning it can be optimized compile time?

**Comment by codeplea** [comment]
I'm working on it now.

**Comment by codeplea** [comment]
Ok, so I added a flag called `TE_FLAG_PURE`. During compilation, any function with that flag set will be optimized out provided that all of it's parameters are `TE_CONSTANT`.

BTW, it doesn't understand commuitive operators. So `a+5+2` does *not* optimize, since the first operation `a+5` cannot complete. However, `a+(5+2)` does optimize to `a+7`.

I've only done limited testing, but it seems to work.

**Comment by EvilPudding** [comment]
I think most C compilers only optimize when you do that.

**Comment by EvilPudding** [comment]
Well... I did it, then I lost it... ;_;

**Comment by codeplea** [comment]
What do you mean? Did you find out that embedding Perl or Python would be a huge pain?

**Comment by EvilPudding** [comment]
No, I did it, but I was working on my master, which had the changes that aren't supposed to be merged to your master yet, so I copied benchmarking.c and the makefile out and reset the master branch, only to find out I copied from the wrong branch, and lost all my work...

**Comment by codeplea** [comment]
Oh, crap. That sucks.

Do you have any preliminary results? Which was fastest?

**Comment by codeplea** [comment]
You said you use vim earlier. You know it makes backups by default, right? Did you look for the swp file?

**Comment by EvilPudding** [comment]
Python was taking about four times more time, but I was parsing the result from a string into a double, when removing that parsing time, it was about three times slower than TE.
Vim keeps a swp file for when it crashes, I exited it correctly, so it deleted the swp file.
It was my failure.

**Comment by codeplea** [comment]
Thanks for the feedback. Nice to know I'm somehow faster than expected. In fact, three times faster is really impressive, in my opinion.

I guess I've always used `set backupdir=XXX` in my `_vimrc`. I forgot it wasn't set by default. It's saved me a couple times. Sucks that you lost your code.

**Comment by codeplea** [comment]
Thanks for the feedback. Nice to know I'm somehow faster than expected. In fact, three times faster is really impressive, in my opinion.

I guess I've always used `set backupdir=XXX` in my `_vimrc`. I forgot it wasn't set by default. It's saved me a couple times. Sucks that you lost your code.

**Comment by EvilPudding** [comment]
Never used that, maybe I'll start.
