### ISSUE TITLE
Software version and tagged release?

### ISSUE THREAD

**Issue by sloretz** [codeplea/tinyexpr#42]
I haven't found a software version number, and there don't appear to be any git tags with releases. Having a version number included in the header file would make it easier to tell if the library is up to date.

In the case that `tinyexpr.h` is installed instead of copied into a project, a version number inside a pre-processor define would allow conditionally working around bugs that may be present in older versions.

Would the maintainer be willing to add a version number?

**Comment by EvilPudding** [comment]
A bit unrelated, but I never copy small libraries into my project, instead I always add it as a git submodule, which allows git to track the version and allows me to update it when I want. It would be even better if there was a branch with nothing but the files usually copied into projects, but it's not necessary.
