### ISSUE TITLE
no variable assigning?

### ISSUE THREAD

**Issue by mgood7123** [codeplea/tinyexpr#43]
why isnt there the ability to do something like "a=2*4" "b=a+4" "c=a*b" or "a = 8 + 5; b=a+4"

**Comment by codeplea** [comment]
I prefer to keep the code-base small so that it's easy for people to add features like that as they need them. If it's going to be called **tiny**expr, I have to draw the line somewhere.

**Comment by mgood7123** [comment]
rip ;-;

**Comment by EvilPudding** [comment]
@mgood7123 Why not use an interpreter like Lua for such a use case?

**Comment by vassilisw** [comment]
It would be very useful to be able to do something like `te_compile("**x=x+3**", vars, 2, &err)` though. Can someone advice how to alter the library to support something like this? Where to look at for example...

**Comment by mgood7123** [comment]
so far, Eval11 (another math expression library) can accomplish this

**Comment by mgood7123** [comment]
tho support for external variables is accomplished through modification of the original Eval11 Library, https://github.com/mgood7123/ccr_resources/tree/master/Scripts/vcpu/eval11, in files 

https://github.com/mgood7123/ccr_resources/blob/master/Scripts/vcpu/eval11/evalwrap.c

https://github.com/mgood7123/ccr_resources/blob/master/Scripts/vcpu/eval11/evaldemo.c

**Comment by mgood7123** [comment]
an example of this is Expression_Assign("s", &test);

**Comment by mgood7123** [comment]
in

https://github.com/mgood7123/ccr_resources/blob/d01b6d77e3c50776a004d687c6506eae54f8a787/Scripts/vcpu/eval11/evaldemo.c#L58

and

https://github.com/mgood7123/ccr_resources/blob/d01b6d77e3c50776a004d687c6506eae54f8a787/Scripts/vcpu/eval11/evalwrap.c#L115
