### ISSUE TITLE
Compiling with GCC < 4.6

### ISSUE THREAD

**Issue by cschreib** [codeplea/tinyexpr#44]
I have just had a user reporting they could not build my project because of ```tinyexpr.c``` refusing to compile. The reason why was that they were using GCC 4.4.7. Indeed, exploring this with godbolt.org, I found that GCC < 4.6 will not compile TinyExpr when the ```-ansi``` option is set. This would seem like correct behavior, because you use an anonymous union in the ```te_expr``` structure, which is a feature only available with the C11 standard, and it should not compile in ANSI C. Intriguingly, GCC only started supporting C11 in versions >= 4.6, so GCC 4.4 should not be able to compile this anyway. I suppose it does only because anonymous unions also happen to be a GNU extension, which gets enabled if ```-std=gnu99``` (indeed, the default in GCC 4.4).

Why GCC >= 4.6 accepts this as valid ANSI code, I have no idea. Sounds like a bug to me.

I ended up fixing the issue by removing the ```-ansi``` option from the compiler options (in the CMake scripts I have at https://github.com/cschreib/tinyexpr). Given that TinyExpr uses some features from C11, it seems that specifying ```-ansi``` was indeed incorrect, but given the mess above I'm happy to hear your opinion on this. I suppose a proper implementation would explicitly ask for ```-std=c11``` for GCC >= 4.6 and ```-std=gnu99``` for GCC < 4.6. But it seems that dropping ```-ansi``` effectively does that, so...
 
Anyway, I thought you might want to consider making this modification for the Makefile as well, hence the issue.

**Comment by codeplea** [comment]
Thanks for the report. I'll look into more when I have time.

I could probably just name the unions and bring it back to ANSI standard.

**Comment by codeplea** [comment]
I've removed -ansi from the Makefile.
