### ISSUE TITLE
Undefined reference to `te_interp`

### ISSUE THREAD

**Issue by amiralisalimi** [codeplea/tinyexpr#45]
Hello, and thank you for your good parser.
I am trying to use this parser in my project, And I'm receiving  this error:
`/tmp/ccqoOUPZ.o: In function 'cexpGen':
/home/amirali/MPSC/projects/c-exp/main.c:56: undefined reference to 'te_interp'
collect2: error: ld returned 1 exit status
The terminal process terminated with exit code: 1`
I've added tinyexpr.h and tinyexpr.c to my project folder, And added :`#include "tinyexpr.h"` to my main.c.

Here is my code:
[https://github.com/amiralisalimi/c-exp](https://github.com/amiralisalimi/c-exp)

**Comment by EvilPudding** [comment]
How are you compiling?

**Comment by amiralisalimi** [comment]
gcc -g main.c -lm

**Comment by amiralisalimi** [comment]
> How are you compiling?

`gcc -g main.c -lm`

**Comment by EvilPudding** [comment]
You're not including tinyexpr. Try:
`gcc -g main.c tinyexpr.c -lm`

**Comment by amiralisalimi** [comment]
It worked, Thank you

**Comment by Ramanbaral** [comment]
It worked for me too. Thank you @EvilPudding
