### ISSUE TITLE
Problem when having more than 2 variables and some not used

### ISSUE THREAD

**Issue by Alexxxxissssssss** [codeplea/tinyexpr#48]
Hi, i'm having some issues with tinyexpr.

The problem is in this configuration : 

variables : 
 - rt = 6000
 - temp = 0
 - rh = 1000
 - hum = 0

Expressions : 
 "log10(rt)" => Ok with good result
 "log10(temp)" => Nan  : OK
 "log10(rh)" => error near ")"
 "log10(hum)" => error near ")"

if i remove rt from my variables:
 "log10(temp)" => Nan : OK
 "log10(rh)" = Ok with good result
 "log10(hum)" => error near ")"

if i remove rt and temp from my variables:
 "log10(rh)" = Ok with good result
 "log10(hum)" => Nan  : OK

So it seems that if i have more than 2 variables and the variable used in the expression is after the second one the tinyexpr can't compile the expression...

Thansk for your help.

**Comment by codeplea** [comment]
It would be a lot more helpful if you could post the smallest, complete code that shows your problem. My guess is that you're not passing in the variables properly. Maybe when you're adding/removing variables you forgot to update the call to `te_compile()`?

**Comment by Alexxxxissssssss** [comment]
What i'm doing is initialiazing the variables table then i've a loop for each expression :

te_variable vars[20];

loop on variables{
vars[i].name = calloc(strlen(varName), sizeof(char));
memcpy(&vars[i].name[0],varName,strlen(varName));
vars[i].address = &varValue[i];
}

*n = te_compile("log10(hum)", vars, nbVars,&err);

if(n){
    te_eval(n)
}


And in te_compile i've added : 

    printf("Exp : %s\n",expression);
    for(int i=0;i<var_count;i++){
		printf("Var Name : %s\n",variables[i].name);
		printf("Var address : %d\n",variables[i].address);
    }

The output is : 
Exp : -39.6+rt*0.01
Var Name : rt
Var address : 152562224
Var Name : temp
Var address : 152562264
Var Name : rh
Var address : 152562304
Var Name : hum25
Var address : 152562344
Var Name : hum
Var address : 152562384
Var Name : dp
Var address : 152562424
So I know that my expression and variables are initialised.

**Comment by Alexxxxissssssss** [comment]
Here is an output i have with complete expressions : 
`
Exp : -39.6+rt*0.01
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Evaluating:
        -39.6+rt*0.01
Result:
        25.360000
Exp : temp
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Evaluating:
        temp
Result:
        -0.000000
Exp : -4+0.0405*rh-(0.0000028*rh^2)
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Evaluating:
        -4+0.0405*rh-(0.0000028*rh^2)
                                                     ^
Error near here
        Error at : 26
Exp : hum25
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Evaluating:
        hum25
                 ^
Error near here
        Error at : 4
Exp : (temp-25)*(0.01+0.00008*rh)+hum25
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Evaluating:
        (temp-25)*(0.01+0.00008*rh)+hum25
                                                    ^
Error near here
        Error at : 26
Exp : hum
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Evaluating:
        hum
            ^
Error near here
        Error at : 2
Exp : ((log10(hum)-2)/0.4343+(17.62*temp)/(243.12+temp))
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Evaluating:
        ((log10(hum)-2)/0.4343+(17.62*temp)/(243.12+temp))
                           ^
Error near here
        Error at : 11
Exp : 243.12*dp/(17.62-dp)
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Evaluating:
        243.12*dp/(17.62-dp)
                        ^
Error near here
        Error at : 9
`

**Comment by codeplea** [comment]
```
te_variable vars[20];

loop on variables{
vars[i].name = calloc(strlen(varName), sizeof(char));
memcpy(&vars[i].name[0],varName,strlen(varName));
vars[i].address = &varValue[i];
}
```

The `name` field should be null terminated. That's probably it right there, as it causes the variable lookup to fail randomly based on what uninitialized memory reads.

Otherwise, I really need a complete, but minimal example to help. Try null terminating that name field. That will probably fix it. If it doesn't, post a complete, but minimal example that exhibits your problem.

**Comment by Alexxxxissssssss** [comment]
`for(int i=0;i<stCurrentLoggerStatus.loggerNbVariables;i++){
		printf("Logger var name : %s\n",stCurrentLoggerStatus.loggerVariables[i].s_VarName);
		printf("Size : %d\n",strlen(stCurrentLoggerStatus.loggerVariables[i].s_VarName));
		vars[i].name = calloc(strlen(stCurrentLoggerStatus.loggerVariables[i].s_VarName)+1, sizeof(char));
		memcpy(&vars[i].name[0],stCurrentLoggerStatus.loggerVariables[i].s_VarName,strlen(stCurrentLoggerStatus.loggerVariables[i].s_VarName));
		if(stCurrentLoggerStatus.loggerVariables[i].i_Length > 0 && stCurrentLoggerStatus.loggerVariables[i].i_blockID == i_blockNumber){
			if(stCurrentLoggerStatus.loggerSN[0] == 'L' && stCurrentLoggerStatus.loggerSN[1] == 'O'){
				stCurrentLoggerStatus.loggerVariables[i].d_VarValue = GetNBitsFromPos(&_pst_frame->acPayload[0], stCurrentLoggerStatus.loggerVariables[i].i_Length, stCurrentLoggerStatus.loggerVariables[i].i_StartsAt);
			}
			else{
				stCurrentLoggerStatus.loggerVariables[i].d_VarValue = GetNBitsFromPos(&_pst_frame->acPayload[1], stCurrentLoggerStatus.loggerVariables[i].i_Length, stCurrentLoggerStatus.loggerVariables[i].i_StartsAt);
			}
			printf("Var value : %f\n",stCurrentLoggerStatus.loggerVariables[i].d_VarValue);
			printf("Var add : %d\n",&stCurrentLoggerStatus.loggerVariables[i].d_VarValue);
		}
		vars[i].address = &stCurrentLoggerStatus.loggerVariables[i].d_VarValue;
		printf("Var Name : %s\n",vars[i].name);
		printf("Var address : %d\n",vars[i].address);

	}

	for(int j=0;j<stCurrentLoggerStatus.loggerBlocks[i_blockNumber].i_SensorsCount;j++){
		for(int i=0;i<stCurrentLoggerStatus.loggerBlocks[i_blockNumber].st_sensors[j].d_nbExpress;i++){
			 printf("Evaluating:\n\t%s\n", stCurrentLoggerStatus.loggerBlocks[i_blockNumber].st_sensors[j].st_MxParserExpressions[i].s_Expression);
			 te_expr *n = te_compile(stCurrentLoggerStatus.loggerBlocks[i_blockNumber].st_sensors[j].st_MxParserExpressions[i].s_Expression, vars, stCurrentLoggerStatus.loggerNbVariables, &i_err);

			 if(n){
				 if(stCurrentLoggerStatus.loggerBlocks[i_blockNumber].st_sensors[j].st_MxParserExpressions[i].s_VarName[0] != 0){
					 ST_VARIABLES* var = LST_GetVarByName(stCurrentLoggerStatus.loggerBlocks[i_blockNumber].st_sensors[j].st_MxParserExpressions[i].s_VarName);
					 printf("Var Name : %s\n", var->s_VarName);
					 r  = var->d_VarValue = te_eval(n);
					 printf("Result:\n\t%f\n", r);
				 }
				 else{
					 r = te_eval(n);
					 printf("Result:\n\t%f\n", r);
				 }
				 te_free(n);
			 } else {
				 /* Show the user where the error is at. */
				 printf("\t%*s^\nError near here \n", i_err-1, "");
				 printf("\tError at : %d \n", i_err-1);
			 }
		}
	}
	for(int i=0;i<stCurrentLoggerStatus.loggerNbVariables;i++){
		free(vars[i].name);
	}`

and here is the output : 

> Logger var name : rt
Size : 2
Var value : 6482.000000
Var add : -1254091272
Var Name : rt
Var address : -1254091272
Logger var name : temp
Size : 4
Var Name : temp
Var address : -1254091232
Logger var name : rh
Size : 2
Var value : 1022.000000
Var add : -1254091192
Var Name : rh
Var address : -1254091192
Logger var name : hum25
Size : 5
Var Name : hum25
Var address : -1254091152
Logger var name : hum
Size : 3
Var Name : hum
Var address : -1254091112
Logger var name : dp
Size : 2
Var Name : dp
Var address : -1254091072
Evaluating:
        -39.6+rt*0.01
Exp : -39.6+rt*0.01
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Var found : rt
END
Var Name : temp
Result:
        25.220000
Evaluating:
        temp
Exp : temp
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Var found : temp
END
Result:
        25.220000
Evaluating:
        -4+0.0405*rh-(0.0000028*rh^2)
Exp : -4+0.0405*rh-(0.0000028*rh^2)
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Var found : rh
Brace open
Var found : rh
Brace closed
END
Var Name : hum25
Result:
        34.466445
Evaluating:
        hum25
Exp : hum25
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Var found : hum25
END
Type : 26
TOK not opened
            ^
Error near here
        Error at : 4
Evaluating:
        (temp-25)*(0.01+0.00008*rh)+hum25
Exp : (temp-25)*(0.01+0.00008*rh)+hum25
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Brace open
Var found : temp
Brace closed
Brace open
Var found : rh
Brace closed
Var found : hum25
END
Type : 26
TOK not opened
                                        ^
Error near here
        Error at : 32
Evaluating:
        hum
Exp : hum
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Var found : hum
END
TOK not closed 4
          ^
Error near here
        Error at : 2
Evaluating:
        ((log10(hum)-2)/0.4343+(17.62*temp)/(243.12+temp))
Exp : ((log10(hum)-2)/0.4343+(17.62*temp)/(243.12+temp))
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Brace open
Brace open
Brace open
Var found : hum
Brace closed
TOK not closed 4
TOK not closed 3
TOK not closed 3
TOK not closed 3
                   ^
Error near here
        Error at : 11
Evaluating:
        243.12*dp/(17.62-dp)
Exp : 243.12*dp/(17.62-dp)
Var Name : rt
Var address : -1254091272
Var Name : temp
Var address : -1254091232
Var Name : rh
Var address : -1254091192
Var Name : hum25
Var address : -1254091152
Var Name : hum
Var address : -1254091112
Var Name : dp
Var address : -1254091072
Var found : dp
TOK not closed 4
                 ^
Error near here
        Error at : 9

>

**Comment by Alexxxxissssssss** [comment]
Iv'e finally found the problem !

This was because of the variables indeed but not because they were not null terminated but because of the type...
In the example you initialise the struct like this : 
  te_variable vars[] = {{"x", &x}, {"y", &y}};
but in my case I'm parsing a text to know which variables I have then i add them one by one to the table.

The parameters set are only the name and the address 
In your example the C set to 0 by default the reste of the struct so each variable as a type to 0 (TE_VARIABLE)
But in an environment like mine where you can't know the variables when coding, you must also set the type to 0...
Maybe you should explain it in the example or force it in te_compile() for each variable :) Because I had to run your code step by step to identify this problem :s
