### ISSUE TITLE
"fatal error LNK1561: entry point must be defined" When using in a C++ library

### ISSUE THREAD

**Issue by PPRhuM** [codeplea/tinyexpr#49]
I get this LINK error when including tinyexpr.h and tinyexpr.c files in a dynamic library C++ project.
The project can't compile.

Is it a configuration mismatch or does the "#ifdef __cplusplus extern "C" { #endif" has a problem ?

I'm using Visual studio 2015.

**Comment by PPRhuM** [comment]
Sorry, juste a project configuration problem.
It do the job really as expected. Thank you for this small but efficient library

**Comment by codeplea** [comment]
Thanks for the update. I'm glad you got it working.
