### ISSUE TITLE
Comparison with muparser

### ISSUE THREAD

**Issue by cignoni** [codeplea/tinyexpr#5]
I love single file libraries, but it should be clear the performance of the lib with respect to the other common choices like muparser ( http://muparser.beltoforion.de/ ).

Could you add a very simple comparison?
Thanks!

**Comment by codeplea** [comment]
Hi cignoni,

You can add muParser to the `benchmark.c` test with the following code:

```C
    printf("muParser ");
    mu::Parser p;
    p.DefineVar("a", &tmp);
    p.SetExpr(expr);

    start = clock();
    d = 0;
    for (j = 0; j < loops; ++j)
        for (i = 0; i < loops; ++i) {
            tmp = i;
            d += p.Eval();
        }
    const int pelapsed = (clock() - start) * 1000 / CLOCKS_PER_SEC;

    /*Million floats per second input.*/
    printf(" %.5g", d);
    if (pelapsed)
        printf("\t%5dms\t%5dmfps\n", pelapsed, loops * loops / pelapsed / 1000);
    else
        printf("\tinf\n");
```

What you'll probably find is that muParser is generally a bit faster than TinyExpr.

As I said in the Readme, speed was never a primary design goal for TinyExpr. I think TinyExpr is fast, but it was much more important for me to make it simple.

I think the other thing to consider is that TinyExpr is in C; muParser is C++. TinyExpr is in one source file and one header file; muParser is 23 source and header files. TinyExpr is about 500 lines of code; muParser is over 10,000 lines of code.

Also, this is just my opinion, but if you want to go in and hack the code to do something else, I think you'll have a much easier time navigating TinyExpr. It's simpler.

**Comment by EvilPudding** [comment]
I can't see why it would be faster, I'll take a look.
If we could optimize speed while keeping the code small and accessible, it would be better, even if not the main goal.
As stated before, muParser is C++, rendering it useless in my projects, the only thing it's got going for it, at a quick glance, is the objectively superior Allman indentation style :)

**Comment by cignoni** [comment]
Thanks for the answers!
I agree that tinylib are quite useful and interesting, I was just asking if there is some penalties and what are their magnitudes. 
Cheers
p.

**Comment by codeplea** [comment]
>I can't see why it would be faster, I'll take a look.
It looks like muParser compiles to byte-code and then executes on a stack-based virtual machine. It also does a lot of algebraic optimizations. It will apparently optimize something like `2*(3*b+1)` to `6*b+2`. That actually seems a bit scary because it's ignoring floating point precision problems.

>If we could optimize speed while keeping the code small and accessible
I'm open to ideas.

>there is some penalties and what are their magnitudes.
I'm resisting talking about magnitudes, because it depends a lot on what you're doing. If your expression is doing a square-root or trigonometry, then you won't notice any difference at all. If your expression is a bunch of basic arithmetic, then muParser may be a couple times faster.

**Comment by EvilPudding** [comment]
Compiling to byte-code? I had thought of that as an option for my projects before accepting to use a tree parser, because I thought you needed to walk around with a compiler for that to work. How is that accomplished?
