### ISSUE TITLE
Bytecode interpreter?

### ISSUE THREAD

**Issue by Kerndog73** [codeplea/tinyexpr#50]
TinyExpr is currently an AST walking interpreter. Interpreting bytecode might be a little faster. If you want competitive speed then JITing is the way to go but then this library will nolonger be tiny, simple or cross-platform. I haven't done any benchmarks with a mock bytecode interpreter but it might be worthwhile. I'd be glad to implement it myself (it sounds like a fun challenge!).

I'll do some benchmarks and see if this makes sense.

**Comment by Kerndog73** [comment]
I benchmarked it...

```
Expression: (1/(a+1)+2/(a+2)+3/(a+3))
native  5.2226e+05	 1115ms	   89mfps
bycode  5.2226e+05	 3185ms	   31mfps
interp  5.2226e+05	 8322ms	   12mfps
```

---

I wrote a bytecode interpreter that with five instructions (add, div, load, const, ret). I hand wrote the bytecode using perfect register allocation (using four registers). Using a stack instead of registers will make generating the bytecode so much easier (because we won't have to worry about register allocation, you just push and pop). Although a stack will be a little slower.

This is the interpreter:

```C
enum OpCode {
  OP_ADD,
  OP_DIV,
  OP_LOAD,
  OP_CONST,
  OP_RET
};

typedef struct Instr {
  unsigned char op;
  unsigned char arg0;
  unsigned char arg1;
  unsigned char out;
  /* Instructions should be aligned to 8 bytes so we can store doubles in the instruction stream */
  unsigned char padding[4];
} Instr;

double interpret(Instr *instr, double **vars) {
  double reg[16];
  while (1) {
    switch (instr->op) {
      case OP_ADD:
        reg[instr->out] = reg[instr->arg0] + reg[instr->arg1];
        ++instr;
        break;
      case OP_DIV:
        reg[instr->out] = reg[instr->arg0] / reg[instr->arg1];
        ++instr;
        break;
      case OP_LOAD:
        reg[instr->out] = *vars[instr->arg0];
        ++instr;
        break;
      case OP_CONST: {
        unsigned char out = instr->out;
        ++instr;
        reg[out] = *(double*)instr;
        ++instr;
        break;
      }
      case OP_RET:
        return reg[instr->arg0];
    }
  }
}
```

A stack-based interpreter is probably the way to go. The add instruction would just pop twice, add and then push. Given this expression `4 / (a + 2)`, you would parse it into an AST that looks like this:

```
   div
  /   \
 4     add
      /   \
  load     2
    |
    a
```

Then, you do a depth-first traversal of the AST to produce bytecode that might look a little bit like this:

```
push 4
load a
push 2
add
div
ret
```

Interpreting this with `a = 6` would look like this:

```
[]
push 4
[4.0]
load a
[4.0, 6.0]
push 2
[4.0, 6.0, 2.0]
add
[4.0, 8.0]
div
[0.5]
ret
0.5
```

The benchmark shows the best possible scenario. Interpreting bytecode will probably be faster than AST walking in all cases but it's hard to say just how much faster until we have a full working implementation. 

I'll start implementing this and open a pull request if I get the go-ahead.

**Comment by EvilPudding** [comment]
How would this look in conjunction with user defined functions?

**Comment by Kerndog73** [comment]
@EvilPudding There will be a call instruction that pops arguments and calls the function. The function pointer would be embedded in the instruction array after the call instruction. A pointer to a variable is embedded in the instruction array after a load instruction. A double is embedded in the instruction array after a push instruction.

**Comment by codeplea** [comment]
You can probably speed up your VM with computed gotos. Basically you put function addresses in an array - the array index is the opcode. You're definitely correct that a stack based VM is much easier. In that case, the parser should use the [shunting-yard algorithm](https://en.wikipedia.org/wiki/Shunting-yard_algorithm).

I'm implemented stack-based VMs/interpreters several times for work (I should probably see if I can open-source one of them). The reason I chose recursive descent for TinyExpr is because it's simple and easy to hack.

I think you should continue on if you're having fun. However, I don't see merging this with TinyExpr since it would be an almost entire rewrite. Rather, you should probably post your code as an entirely new project (or a fork of TinyExpr if you do use parts of it). If you kept the interface from TinyExpr, then people using TinyExpr could just drop in your code and get a speed-up. That might be cool.

**Comment by Kerndog73** [comment]
Ah, the shunting yard algorithm. I forgot about that. So much better than recursive decent parsing and then a depth-first traversal. Computed goto seems like a great idea.

I realise that this would be a complete rewrite of the library for a tiny speed boost. I'm just gonna start my own project and make a VM for the fun of it!

**Comment by codeplea** [comment]
Let me know when you have something working. I'd be interested to see what you come up with.

**Comment by Kerndog73** [comment]
@codeplea Sure. Whatever I make will be on GitHub.

**Comment by Kerndog73** [comment]
@codeplea I just threw [something](https://github.com/kerndog73/expr-jit) together. I haven't properly tested it. It has pretty much the same API as TinyExpr while also being roughly the same amount of code. The difference is that parentheses are always required when calling a function so `sqrt(25)` must be written instead of `sqrt 25`. Also, mine is written in C99.

**Comment by codeplea** [comment]
I haven't had time to try it, but it looks pretty good. Congrats on finishing it!
