### ISSUE TITLE
Cant use it in C++

### ISSUE THREAD

**Issue by Kritip123** [codeplea/tinyexpr#58]
I want to use it in C++ programs. Please develop a program such that it can be used in C++ as well.
For the c program which do not run in c++, refer to this link and upload a new file soon please...
https://www.geeksforgeeks.org/write-c-program-wont-compiler-c/

**Comment by codeplea** [comment]
Compile it as C, then link it with your C++ project. This is trivial and the normal way of doing these things.

**Comment by Kritip123** [comment]
The project is c++ how can I compile it using c++.....please tell me the steps

**Comment by Kritip123** [comment]
I am running the cpp file using 
g++ -g project.cpp tinyexpr.c -lm

**Comment by Kritip123** [comment]
What is the correct way...  Help me out plzz

**Comment by EvilPudding** [comment]
You need to compile each of them, then link, something like:
``` g++ -g -c project.cpp -o project.o
cc -g -c tinyexpr.c -o tinyexpr.o
g++ project.o tinyexpr.o -lm -o executable```
