### ISSUE TITLE
Compilation error with Visual studio 2012

### ISSUE THREAD

**Issue by jherkel** [codeplea/tinyexpr#7]
There is a problem with this code "0.0/0.0". Correct form is this define
#define NAN        ((float)(INFINITY * 0.0F))  (from math.h)

**Comment by codeplea** [comment]
The NAN macro isn't universally defined. I changed the code so that it checks if NAN is defined, and if so uses that.

I don't have Visual Studio, could you try the new change and let me know if it works?

**Comment by codeplea** [comment]
jherkel, can you confirm that the fix works?

**Comment by jherkel** [comment]
Sorry for the late response, I had to reinstall my computer. I can confirm your fix works.

**Comment by codeplea** [comment]
Thanks for the reply. I'm glad it works.
