### ISSUE TITLE
Parse expression, get variable list

### ISSUE THREAD

**Issue by EvilPudding** [codeplea/tinyexpr#8]
This is a feature request, which I can't seem to be able to implement
without making way too many changes, I need a function which only receives
the `const char *` expression and returns the array of variables used in such
expression.

```c
te_variable *te_get_variables(const char *expression, int *var_count);
```

The purpose of this, is that I want the user to be able to define the
variables just by using them, and I don't think it would be practical to be
using a separate parser, when this library already has it implemented.
Having this array, then I could easily allocate the `double` memory for the
values, then assign and feed the array to te_compile.

**Comment by codeplea** [comment]
I think this logic is out of the scope of TinyExpr. However, I can think of a couple easy ways to solve your problem.

First option is to just implement a tokenizer. For example, this code will print out each identifier in an expression:

```C
void print_identifiers(const char *expr) {
    while (*expr) {
        while (*expr && (*expr < 'a' || *expr > 'z')) ++expr;
        const char *start = expr;
        if (*expr >= 'a' && *expr <= 'z') {
            while ((*expr >= 'a' && *expr <= 'z') || (*expr >= '0' && *expr <= '9')) ++expr;
            printf("%.*s\n", expr-start, start);
            ++expr;
        }
    }
}

print_identifiers("a+b17*cat-dog(-3)*x"); /* prints: a b17 cat dog x */
```

Another option would be to put a callback in the `next_token()` function that gets called when a variable lookup fails (after both `find_lookup()` and `find_builtin()` fails.. That would be an easy way to get a callback for each unknown variable name. You could have your callback function just return 0 for the first parse-though, then create your `TE_VARIABLE` structure and reevaluate. Or you could just have the callback lookup and return the variable value at runtime, thus avoiding using the `TE_VARIABLE` structure at all.

I could see either option working pretty well, depending on your use case.

**Comment by EvilPudding** [comment]
The first one really does not work, because the tokens might be functions or constants like `pi` or `e`, and everytime the library changed, I would have to change the tokenizer as well, while if the library gave me the variables it will need, then it would always work.

I had thought of the second option as well, though that means changing the library as well, would I have to keep a patched version, or would this callback system be merged?

**Comment by codeplea** [comment]
Help me understand your use-case better. Where are the variable values coming from? I don't understand how you can not know a variable exists, but still know its value.

**Comment by EvilPudding** [comment]
I have a node system that before trying to resolve the result of each node,
you can connect inputs and outputs which are called fields, each node has a
struct, and each field is associated with a value in such struct. There is
a particular node called Expression, that contains a string called `expr`
and `value` `x` `y` `z` `w` `t` variables, each points to a double in the
struct, that when solving will generate the `te_variable` array pointing to
each of those doubles, and will store the result in `value`, however, I
don't want those variables to be hard-coded, but instead allocated when the
user types them into the expression, so I have removed the `x` `y` `z` `w`
`t` from the node, leaving it with only the `expr` and `value`, and added
to the structure a `te_variable` array, and an `int` for it's size. Now I
must fill this array whenever the `expr` changes.

Don't know if I was able to explain in an understandable way, it's a bit
complex.

**Comment by codeplea** [comment]
Why not use the code I posted above and look for the existence of `x`, `y`, `z`, `w`, or `t`? You would just run it as a pre-pass, and create the `TE_VARIABLE` array then. Then you compile with TinyExpr to actually check for proper syntax as a second step. I don't see how putting the functionality into TinyExpr itself adds any advantage.

It's true that the above code can't determine between a variable and a function, but that check would be made during the `te_complie()` call. I don't see why you'd need a list of the builtin functions either, just look only for `x`, `y`, etc and ignore anything else. (again, it'll get caught by `te_compile()` if it's a problem.

I don't really want to add the functionality you're talking about into TinyExpr unless there is no simple way to do it outside of TinyExpr. Also, a key feature of tinyexpr is the "Tiny" part.

**Comment by EvilPudding** [comment]
You misunderstand, having `x` `y` `z` `w` `t` was a workaround, because the node's fields had to be static, then I worked to make them dynamic, I don't want the variables to be just those, I want them to be any word a user writes in the expression, and if the word is a variable, meaning it is not recognized as a function or constant, it is supposed to add that variable as a field to the specific node.

When a user inserts, for example "red + green / blue * pow(black * pi)", I need to get the list `{"red", "green", "blue", "black"}`, if I use the method you suggested, I would get the list `{"red", "green", "blue", "pow", "black", "pi"}`. The list I want is supposed to be the words that will be considered variables by TinyExpr.

**Comment by codeplea** [comment]
Let me see if I understand. If the user enters `red + green / blue * pow(black * pi, 2)`, you want to parse that and then ask the user for the values of `red`, `green`, etc? After the user tells you the values for all the variables, then you re-evaluate the expression?

An issue is that TinyExpr can't tell the difference between a variable and a functional call until it's parsed well past it. Currently TinyExpr doesn't do any backtracking. So I don't think it's possible to get an expression and say, look here's the missing variables in one pass. The best you could hope for is adding an extra callback after `find_builtin()` fails.

I still think this is better done externally to TinyExpr. For example, here is code to iteratively try an expression by adding missing variable until it compiles (or finds an actual syntax error):

```C
int main(int argc, char *argv[])
{
    const char *expr = "red + green / blue * pow(black * pi, 2)";

    int err;
    te_variable vars[10] = {0};
    int var_count = 0;

    do {
        te_expr *e = te_compile(expr, vars, var_count, &err);

        if (err) {
            /* Check if the error is a missing variable. */
            const char *start = expr + err;
            while (start > expr && (start[-1] >= 'a' && start[-1] <= 'z')) --start;
            const int len = expr + err - start;
            if (len) {
                printf("New variable. Please enter the value for '%.*s': ", len, start);
                char *var_name = malloc(len + 1);
                memcpy(var_name, start, len);
                var_name[len] = 0;
                vars[var_count].name = var_name;
                double *val = malloc(sizeof(double));
                scanf("%lf", val);
                vars[var_count].address = val;
                ++var_count;
            } else {
                /* Nope, error is something real. */
                printf("Syntax error near %d\n", err);
                return 1;
            }
        } else {
            printf("Success!\n");
            printf("Result: %f\n", te_eval(e));
            te_free(e);
        }

    } while (err && var_count < 10);

    /* TODO free name and values in vars array. */

    return 0;
}
```

By the way, I discovered a small bug with how TinyExpr handles bad expressions. You'll want to do a git pull.

**Comment by EvilPudding** [comment]
It's the closest answer to the actual problem, however, this would break if you decided, for example, to add other characters to the possible ones in a variable like "_", "$" or others. And it also looks very inefficient, the start of the expression will be compiled over and over until you have all the variables, It's wasteful, I may use it right now, but later on, I will modify te_compile to allow me to customize the lookup. Thanks anyway, I understand completely why you don't want it as a feature, but the code will be better that way, at least for me, you won't have to merge it.
