### ISSUE TITLE
Result is wayyyy off.

### ISSUE THREAD

**Issue by git-tomb** [codeplea/tinyexpr#81]
I'm getting the output -1048576.459961 for this snippet of code, which should equal 7. What's up with that?

{
		float a, b, c, d, e, f, g;
		const char formula[50] = "5 * b - a * c";
		int err;
		te_variable vr[] = { {"a",&a}, {"b",&b}, {"c",&c}, { "d",&d }, { "e",&e }, { "f",&f }, { "g",&g } };
		const te_expr* expr = te_compile(formula, vr, 7, &err);
		a = 1.0f;
                b = 2.0f;
                c = 3.0f;
                d = 4.0f;
                e = 5.0f;
                f = 6.0f;
                g = 7.0f;
                printf("%lf\n", te_eval(expr));
	}

Similarly, a+b+c = 32800.015663

I knows it's 2021, but come on:P

**Comment by codeplea** [comment]
Before you edited your code just now, you had:

```
const char formula[50] = "5b-ac";
```
which is a huge problem.

Also, print `err`. That will tell you where the problem is.

**Comment by git-tomb** [comment]
> Before you edited your code just now, you had:
> 
> ```
> const char formula[50] = "5b-ac";
> ```
> 
> which is a huge problem.
> 
> Also, print `err`. That will tell you where the problem is.

Yeah, the forum formatting changed "5*b-a*c" to italics.

err is 0.

**Comment by codeplea** [comment]
Have you modified tinyexpr.c? It expects variables to be `double` by default, not `float`.

**Comment by git-tomb** [comment]
I made some minor modifications just to wipe out some warnings.

Looks like float/double is the problem. Unusual. Thanks.
