### ISSUE TITLE
codeblocks compiler issue?

### ISSUE THREAD

**Issue by Bitsepp** [codeplea/tinyexpr#89]
That's what I get when I compile the "tinyexpr.c" in a new C project in codeblocks environment (console appl):

||=== Build: Debug in tinyexpr (compiler: GNU GCC Compiler) ===|
/usr/bin/ld: obj/Debug/tinyexpr.o||in function `next_token':|
/home/baudi/alex/codeblocks/tinyexpr/tinyexpr.c|289|undefined reference to `pow'|
/usr/bin/ld: /home/baudi/alex/codeblocks/tinyexpr/tinyexpr.c|290|undefined reference to `fmod'|
/usr/bin/ld: obj/Debug/tinyexpr.o||in function `factor':|
/home/baudi/alex/codeblocks/tinyexpr/tinyexpr.c|467|undefined reference to `pow'|
/usr/bin/ld: obj/Debug/tinyexpr.o||in function `term':|
/home/baudi/alex/codeblocks/tinyexpr/tinyexpr.c|484|undefined reference to `fmod'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x8)||undefined reference to `fabs'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x28)||undefined reference to `acos'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x48)||undefined reference to `asin'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x68)||undefined reference to `atan'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x88)||undefined reference to `atan2'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0xa8)||undefined reference to `ceil'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0xc8)||undefined reference to `cos'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0xe8)||undefined reference to `cosh'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x128)||undefined reference to `exp'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x168)||undefined reference to `floor'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x188)||undefined reference to `log'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x1a8)||undefined reference to `log10'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x1c8)||undefined reference to `log10'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x248)||undefined reference to `pow'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x268)||undefined reference to `sin'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x288)||undefined reference to `sinh'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x2a8)||undefined reference to `sqrt'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x2c8)||undefined reference to `tan'|
/usr/bin/ld: obj/Debug/tinyexpr.o:(.data.rel.ro+0x2e8)||undefined reference to `tanh'|
||error: ld returned 1 exit status|
||=== Build failed: 24 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|

**Comment by codeplea** [comment]
Try using the -lm linker flag.

**Comment by Bitsepp** [comment]
yes, that solved the problem. Actually in the linker it's just to add a 'm'
Thank you!
![image](https://user-images.githubusercontent.com/98108532/150546854-f8ece51b-e7a3-4e53-82ad-f6230ac5e456.png)
