### ISSUE TITLE
Error eval expression when initializing te_variable by individual assignment 

### ISSUE THREAD

**Issue by aeonSolutions** [codeplea/tinyexpr#97]
Hi there,
   
   I'm using _tinyexpr_ with the following piece of code 
   
```
    double dt=0.49;
    double p=30.0;

    te_variable vars2[2];

    vars2[0].name=String("p").c_str();
    vars2[0].address= &p;
    vars2[0].type=TE_VARIABLE; 

    vars2[1].name=String("dt").c_str();
    vars2[1].address=&dt;
    vars2[1].type=TE_VARIABLE; 

     te_variable vars3[]= { 
                            {.name="p", .address=&p},  
                            {.name="dt", .address=&dt}
                        };
```

if I use `vars2` I get the error when parsing my expression 

if I use `vars3` parsing is OK and is able to calculate values. 

Could anyone please tell me why this is happening?
thank you

**Comment by aeonSolutions** [comment]
Ok. Got it. Thank you.

I also found 

```
    te_variable vars[]= { 

                            {.name="dt", .address = &dt},  
                            {.name="p", .address = &p},

                        };
```

in 

[    te_expr *n = te_compile(this->config.custom_maturity_equation.c_str(), vars, numVars, &err);](url)


need to have the exact number of elements as there are a number of variables in an expression. This make it really hard to code a function to access any expression with any number of variables

**Comment by codeplea** [comment]
>need to have the exact number of elements as there are a number of variables in an expression. This makes it really hard to code a function to access any expression with any number of variables

You can pass in as many variables as you need. There is no need for the expression to use them all. Also, if the expression is parsed with a variable that isn't included, you can easily set your calling code to see that, then include the variable and call again. It's not hard.

>I could not implement it using an array of const char names and/or double values. I had to declare individual single variable names.

Of course it will work fine with an array vs variable, and furthermore, there is no way for the called function to even tell the difference, even in theory. You must be making an error when calling.

>and it does not accept a global array of values within the same class.

I don't know what you even mean by "global array of values within the same class". What do you even mean by class?

If you want to post a minimal, but complete, example, I'm sure I can spot where you've gone wrong.

**Comment by aeonSolutions** [comment]
I wasn't arguing.  What i stated is the result of 3 days of work debugging this library,

**Comment by aeonSolutions** [comment]
Here's the class function I'm using , right now

```
// ******************* Maturity Models ************************************
double MATURITY_CLASS::custom_maturity(int pos){
    
    //String var[8]= {"a","h","pt","dt","p","m","t","u"};
    //                 0   1    2    3   4   5   6   7

    double a=this->measureValues[0];
    double h=this->measureValues[1];
    double pt=this->measureValues[2];
    double dt=this->measureValues[3];
    double p=this->measureValues[4];
    double m=this->measureValues[5];
    double t=this->measureValues[6];
    double u=this->measureValues[7];

    const char* a_n="a";
    const char* h_n="h";
    const char* pt_n="pt";
    const char* dt_n="dt";
    const char* p_n="p";
    const char* m_n="m";
    const char* t_n="t";
    const char* u_n="u";

    te_variable vars[]= { 
                            {.name=dt_n, .address = &dt},  
                            {.name=p_n, .address = &p}
                        };

    this->mserial->printStrln("custom_maturity");
    
    int numVars = this->get_number_model_vars(this->config.custom_maturity_equation);

    this->mserial->printStrln("number of variables in the model is " + String(numVars));
    

    this->mserial->printStrln("p:"+String(  this->measureValues[4]));
    this->mserial->printStrln("dt:"+String( this->measureValues[3]));
 
 this->mserial->printStrln("here-1");
 this->mserial->printStrln("dt:" + String(dt));
this->mserial->printStrln("here 0");
  this->mserial->printStrln("p:" + String(p));
 this->mserial->printStrln("here 1");
    int err;
    te_expr *n = te_compile(this->config.custom_maturity_equation.c_str(), vars, numVars, &err);
 this->mserial->printStrln("here 3");
    if (n) {
        this->mserial->printStrln("Start fetching values from the database file...");
        double result=0.0;
        for (int i=0; i<(pos+1); i++){
            get_dataset_values(i);
            m=this->custom_maturity(i);
            result += (double) te_eval(n); 
        }
        this->mserial->printStrln("DONE!");

        te_free(n);
        return result;
    } else {
         this->mserial->printStrln("here2");
        this->mserial->printStrln(this->config.custom_maturity_equation + " << error near pos " + String(err-1) );
        return (0.0/0.0);
    }
}
```

**Comment by codeplea** [comment]
>I wasn't arguing. What i stated is the result of 3 days of work debugging this library,

I understand. I'm just trying to help you. You've made some basic mistakes, so I'm just letting you know that these things you believe are limitations actually aren't.

What is your thought process here?

>  int numVars = this->get_number_model_vars(this->config.custom_maturity_equation);

`numVars` must be 2, because `vars` has only two entries.

I think what you want is something like this:

```
    te_variable vars[]= { 
                            {.name="a", .address = this->measureValues + 0},  //This assumes that measureValues is double array!!
                            {.name="h", .address = this->measureValues + 1},  
                            {.name="pt", .address = this->measureValues + 2},  
                            {.name="dt", .address = this->measureValues + 3},  
                            {.name="p", .address = this->measureValues + 4},  
                            {.name="m", .address = this->measureValues + 5},  
                            {.name="t", .address = this->measureValues + 6},  
                            {.name="u", .address = this->measureValues + 7}
                        };
    const int numVars = 8; //This refers only to the number of entries in vars!!

    int err;
    te_expr *n = te_compile(this->config.custom_maturity_equation.c_str(), vars, numVars, &err);
```

**Comment by aeonSolutions** [comment]
ok. great. thank you.  And you are correct. 
Plus in the meantime, I've found my memory leak. This line ` m=this->custom_maturity(I);` should already be deleted !!

again thank you
